### ISSUE TITLE
Generate an .ics file from a schedule

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#100] opened 2016-04-16 19:05 UTC
Add ability to export to iCalendar format for use with calendar applications

**Comment by copperwater** [comment] 2016-09-16 01:16
Removing future tag since this is apparently a fairly commonly requested feature.

**Comment by copperwater** [comment] 2016-10-09 21:23
Removing Backend tag since this can and should be done by the frontend.

**Comment by copperwater** [comment] 2016-10-10 04:18
This is now done, but I have been doing it in the routing framwork so I'm not going to open a pull request until that gets merged into staging.

A couple things that are not implemented and I don't think are important enough to fall under the scope of this issue:
* Courses repeat weekly and never stop, which means anyone who imports an ics into their calendar will end up having to delete it. In order to get a stop date we would have to add some way of passing the end of semester date from RPI through the backend to the schedules API, which is a lot of work for that small feature.
* I don't know if categories should be applied. My test set consisted of Calc 1 and CS 1 which had a lot of broken up periods, and it would have been nice to have them colored differently, but not necessary.

**Comment by copperwater** [comment] 2016-10-26 19:37
This is now in staging, so the issue is finished.

**Closed by copperwater** 2016-10-26 19:37 UTC
Labels: Frontend, new feature
