### ISSUE TITLE
ENGR 2050 Title Incorrect

### ISSUE THREAD

**Issue by kelleyb** [YACS-RCOS/yacs#170] opened 2016-11-07 21:10 UTC
Not sure if it's a parsing error, or something else, but ENGR 2050 is being displayed incorrectly. Humorously so.

![lolyacs](https://cloud.githubusercontent.com/assets/2424142/20075984/95e923b2-a504-11e6-8d42-ff328e7a8f9a.png)

**Comment by copperwater** [comment] 2016-11-07 21:23
Not a bug, just a problem with data entry. It's fixed now, closing this.

**Closed by copperwater** 2016-11-07 21:23 UTC
