### ISSUE TITLE
Create new Catalog adapter interface solution

### ISSUE THREAD

**Issue by JGrippo** [YACS-RCOS/yacs#147] opened 2016-10-09 22:55 UTC
New catalog adapter solution should consist of:
- An interface (abstract class)
- A client

Diffing and updating the database should be generalized and moved to a new catalog client so that this behavior does not have to be re-implemented for different sources. The implementation of the catalog interface is then only responsible for providing the current state of the catalog (to the client).

**Comment by copperwater** [comment] 2016-10-09 22:57
Duplicate of #129

**Closed** 2016-10-09 22:57 UTC
