### ISSUE TITLE
As a student, I would like to see course numbers in the schedule view so that I can better understand the schedule

### ISSUE THREAD

**Issue by kmcnellis** [YACS-RCOS/yacs#91] opened 2016-04-01 15:41 UTC
"Computer Science I CSCI 1100 4 credits" Is show in the search view, but only "Computer Science I" is show in schedule view.

**Comment by aosdict** [comment] 2016-04-01 15:56
On the schedule itself, showing only the course title is the intended behavior. But on the list below it, yes, it should be identical to what you see in the search view. When that part is controlled by Handlebars, it will use the same code and appear the same way.

**Comment by copperwater** [comment] 2016-09-09 20:17
The actual schedule periods were changed over the summer, but the list below the schedule has been using the same template as the course list for a while now, although we eventually intend to replace that. Since I think the original issue has been addressed, I'm closing this.

**Closed by copperwater** 2016-09-09 20:17 UTC
Labels: 1 - Ready For Development, easy
