### ISSUE TITLE
Can't click on course in a list at the bottom of certain departments.

### ISSUE THREAD

**Issue by Malorn44** [YACS-RCOS/yacs#338] opened 2018-10-26 20:50 UTC
NOTE: This issue definitely needs some serious investigation because I have no idea why this would be happening as of this moment.

From what I observed on my end, click a course to select it that was at the bottom of the list doesn't work for certain departments. 
Example departments where it doesn't work: PHIL, STSH
Example departments where it works as expected: STSS

This might not only be happening with the bottom course which is why it needs more investigation. This is just what I had observed.

Extra note: you can still select a course at the bottom of PHIL for example if you click on the section drop-down and click on sections.

**Comment by fakedestinyck** [comment] 2019-02-07 06:22
I think that's not because a course is at the bottom of the list of a department. Just because the class/section is full/close. However, it's definitely not the expected behavior. See #377. That's the issue I'm currently working on.
@Malorn44 @Bad-Science

**Comment by Bad-Science** [comment] 2019-02-08 02:47
@fakedestinyck Makes sense. Let's verify this once #377 is complete and then we can close this as well.

**Comment by Bad-Science** [comment] 2019-03-07 14:02
@fakedestinyck Can we close this now?

**Comment by fakedestinyck** [comment] 2019-03-08 02:31
> @fakedestinyck Can we close this now?

Yes! I think we've solved this problem.

**Closed** 2019-03-08 02:31 UTC
Labels: class:bug, help wanted, priority:critical, service:web, size:large, status:readyfordev
