### ISSUE TITLE
As a student, I would like see a truncated course description by default so that I can view courses more easily

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#105] opened 2016-06-03 19:42 UTC
Made this a separate issue from #90. Before building the expand feature the course description should be truncated.

**Comment by copperwater** [comment] 2016-09-09 02:29
This is a duplicate of #74

**Comment by copperwater** [comment] 2016-09-09 16:59
Not closing until I figure out how this is in the "Vetting" stage since evidently it has been worked on/completed.

**Comment by copperwater** [comment] 2016-09-13 17:37
This is being closed due to its duplicate status. #74 is now the go-to issue for this.

**Closed by copperwater** 2016-09-13 17:37 UTC
Labels: 3 - Vetting <= 3, easy, Frontend
